spring :
  datasource :
    driverClassName : org.mariadb.jdbc.Driver
    url : jdbc:mariadb://localhost:3306/BelajarSpringOauth2
    username : root
    password : root

  jpa :
    hibernate :
      ddl-auto : update

server :
  port : 8888